services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest 
    container_name: ombi
    networks:
      - proxy
    hostname: ombi
    volumes:
      - ./config:/config
      - /media:/media
      - /downloads:/downloads
      - /downloads:/download
    environment:
      - APP_GROUP=Requests
      - APP_LOGO=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ombi.png
      - VIRTUAL_HOST=requests.pknw1.co.uk
      - VIRTUAL_PORT=3579
      - BASE_URL=/requests
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1000M 


networks:
  proxy:
    external: true
    name: proxy
